//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentMgtSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stu
    {
        public string ID { get; set; }
        public string EP { get; set; }
        public string FirstName { get; set; }
        public string MidName { get; set; }
        public string LastName { get; set; }
        public string Department { get; set; }
        public int Year { get; set; }
        public string HomeTown { get; set; }
    }
}
